# Generated by Django 3.2 on 2021-08-31 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventposter', models.ImageField(blank=True, upload_to='eventknowledgecentre/static/imgs/')),
                ('eventname', models.CharField(max_length=100, null=True)),
                ('datetimestart', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('downloadviewlink', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
