# Generated by Django 3.2 on 2021-08-31 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exibitor',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('brochuredownloadlink', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
