# Generated by Django 3.2 on 2021-08-31 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('owner', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.CharField(max_length=50)),
                ('isGroup', models.BooleanField(default=False)),
                ('groupId', models.TextField(blank=True, null=True)),
                ('approval_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=50)),
                ('reader', models.CharField(blank=True, max_length=50, null=True)),
                ('typing_status', models.BooleanField(default=False)),
                ('onGroup', models.BooleanField(blank=True, default=False, null=True)),
                ('groupId', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
